# Generated by Django 5.1.3 on 2024-11-06 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
