# Generated by Django 5.1.3 on 2024-11-10 10:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_consultation_id_alter_diseaseinfo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseForSuggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=200, unique=True)),
                ('good_habits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('good_foods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('notgoodfoods', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
            ],
            options={
                'verbose_name_plural': 'Disease Suggestions',
            },
        ),
    ]
